export const categories = [
  {
    "name": "Concentrate"
  },
  {
    "name": "Equipment"
  },
  {
    "name": "Flower"
  },
  {
    "name": "Trim"
  },
  {
    "name": "Fresh Frozen"
  },
  {
    "name": "Oil"
  },
  {
    "name": "Pre-Roll"
  },
]

export const vendors = [
  {
    "name": "Taylor Farms"
  },
  {
    "name": "Five Grow"
  },
  {
    "name": "Rocky Mountain"
  },
  {
    "name": "Golden Leaf"
  },
  {
    "name": "240 Arthur"
  },
  {
    "name": "Chronic Factory"
  },
  {
    "name": "High Canyon"
  },
  {
    "name": "CannXtracts"
  },
  {
    "name": "Kunubu"
  }
]

export const products = [
  {
    "name": "Blueberry Headband",
    "slug": "blueberry-headband",
    "category": "Flower",
    "price": "650.00",
    "inventory": "4",
    "recreational": true,
    "medical": false,
    "hotDeal": false,
    "topPick": false,
    "status": "AVAILABLE",
    "vendor": "Five Grow",
  },
  {
    "name": "Durban Kush",
    "slug": "durban-kush-fg",
    "category": "Flower",
    "price": "650.00",
    "inventory": "8.7",
    "recreational": true,
    "medical": false,
    "hotDeal": false,
    "topPick": false,
    "status": "AVAILABLE",
    "vendor": "Five Grow",
  },
  {
    "name": "General Tso",
    "slug": "general-tso",
    "category": "Flower",
    "price": "650.00",
    "inventory": "9.4",
    "recreational": true,
    "medical": false,
    "hotDeal": true,
    "topPick": false,
    "status": "AVAILABLE",
    "vendor": "Five Grow",
  },
  {
    "name": "Mandarin Dreams",
    "slug": "mandarin-dreams",
    "category": "Flower",
    "price": "650.00",
    "inventory": "3.5",
    "recreational": true,
    "medical": false,
    "hotDeal": false,
    "topPick": true,
    "status": "AVAILABLE",
    "vendor": "Five Grow",
  },
  {
    "name": "MemberBerry",
    "slug": "memberberry-fg",
    "category": "Flower",
    "price": "650.00",
    "inventory": "4.73",
    "recreational": true,
    "medical": false,
    "hotDeal": false,
    "topPick": false,
    "status": "AVAILABLE",
    "vendor": "Five Grow",
  },
  {
    "name": "Pineapple Chunk",
    "slug": "pineapple-chunk",
    "category": "Flower",
    "price": "650.00",
    "inventory": "1.3",
    "recreational": true,
    "medical": false,
    "hotDeal": true,
    "topPick": false,
    "status": "AVAILABLE",
    "vendor": "Five Grow",
  },
  {
    "name": "Wedding Cake",
    "slug": "wedding-cake-fg",
    "category": "Flower",
    "price": "650.00",
    "inventory": "13.64",
    "recreational": true,
    "medical": false,
    "hotDeal": false,
    "topPick": false,
    "status": "AVAILABLE",
    "vendor": "Five Grow",
  },
  {
    "name": "Jet Fuel Gelato",
    "slug": "jet-fuel-gelato",
    "category": "Flower",
    "price": "500.00",
    "inventory": "5.78",
    "recreational": true,
    "medical": false,
    "hotDeal": false,
    "topPick": true,
    "status": "AVAILABLE",
    "vendor": "Rocky Mountain",
  },
  {
    "name": "Lavender Jones",
    "slug": "lavender-jones",
    "category": "Flower",
    "price": "500.00",
    "inventory": "0.67",
    "recreational": true,
    "medical": false,
    "hotDeal": false,
    "topPick": false,
    "status": "AVAILABLE",
    "vendor": "Rocky Mountain",
  },
  {
    "name": "Lilac Diesel",
    "slug": "lilac-diesel",
    "category": "Flower",
    "price": "500.00",
    "inventory": "4.2",
    "recreational": true,
    "medical": false,
    "hotDeal": true,
    "topPick": false,
    "status": "AVAILABLE",
    "vendor": "Rocky Mountain",
  },
  {
    "name": "Mac N Cheese",
    "slug": "mac-n-cheese",
    "category": "Flower",
    "price": "500.00",
    "inventory": "8.33",
    "recreational": true,
    "medical": false,
    "hotDeal": false,
    "topPick": false,
    "status": "AVAILABLE",
    "vendor": "Rocky Mountain",
  },
  {
    "name": "Monkey Spunk",
    "slug": "monkey-spunk",
    "category": "Flower",
    "price": "500.00",
    "inventory": "3.7",
    "recreational": true,
    "medical": false,
    "hotDeal": true,
    "topPick": true,
    "status": "AVAILABLE",
    "vendor": "Rocky Mountain",
  },
  {
    "name": "Tropicanna Banana",
    "slug": "tropicanna-banana",
    "category": "Flower",
    "price": "500.00",
    "inventory": "2.7",
    "recreational": true,
    "medical": false,
    "hotDeal": false,
    "topPick": false,
    "status": "AVAILABLE",
    "vendor": "Rocky Mountain",
  },
  {
    "name": "Caked Up Cherries",
    "slug": "caked-up-cherries",
    "category": "Flower",
    "price": "1000.00",
    "inventory": "4.66",
    "recreational": true,
    "medical": false,
    "hotDeal": false,
    "topPick": false,
    "status": "AVAILABLE",
    "vendor": "Golden Leaf",
  },
  {
    "name": "Chem Squeezy",
    "slug": "chem-squeezy",
    "category": "Flower",
    "price": "1000.00",
    "inventory": "9.76",
    "recreational": true,
    "medical": false,
    "hotDeal": false,
    "topPick": false,
    "status": "AVAILABLE",
    "vendor": "Golden Leaf",
  },
  {
    "name": "Deluxe Sugar Cane",
    "slug": "deluxe-sugar-cane",
    "category": "Flower",
    "price": "1000.00",
    "inventory": "1.22",
    "recreational": true,
    "medical": false,
    "hotDeal": false,
    "topPick": false,
    "status": "AVAILABLE",
    "vendor": "Golden Leaf",
  },
  {
    "name": "Donny Burger",
    "slug": "donny-burger",
    "category": "Flower",
    "price": "1000.00",
    "inventory": "0.57",
    "recreational": true,
    "medical": false,
    "hotDeal": true,
    "topPick": false,
    "status": "AVAILABLE",
    "vendor": "Golden Leaf",
  },
  {
    "name": "Free MAC",
    "slug": "free-mac-gl",
    "category": "Flower",
    "price": "1000.00",
    "inventory": "3.78",
    "recreational": true,
    "medical": false,
    "hotDeal": false,
    "topPick": true,
    "status": "AVAILABLE",
    "vendor": "Golden Leaf",
  },
  {
    "name": "Gak Slurry",
    "slug": "gak-slurry",
    "category": "Flower",
    "price": "1000.00",
    "inventory": "8.32",
    "recreational": true,
    "medical": false,
    "hotDeal": false,
    "topPick": false,
    "status": "AVAILABLE",
    "vendor": "Golden Leaf",
  },
  {
    "name": "Glitter Bomb",
    "slug": "glitter-bomb",
    "category": "Flower",
    "price": "1000.00",
    "inventory": "11.44",
    "recreational": true,
    "medical": false,
    "hotDeal": true,
    "topPick": false,
    "status": "AVAILABLE",
    "vendor": "Golden Leaf",
  },
  {
    "name": "Lemonhead Delight",
    "slug": "lemonhead-delight",
    "category": "Flower",
    "price": "1000.00",
    "inventory": "1",
    "recreational": true,
    "medical": false,
    "hotDeal": false,
    "topPick": false,
    "status": "AVAILABLE",
    "vendor": "Golden Leaf",
  },
  {
    "name": "Lemon Splash",
    "slug": "lemon-splash",
    "category": "Flower",
    "price": "1000.00",
    "inventory": "3.98",
    "recreational": true,
    "medical": false,
    "hotDeal": false,
    "topPick": true,
    "status": "AVAILABLE",
    "vendor": "Golden Leaf",
  },
  {
    "name": "MemberBerry",
    "slug": "memberberry-gl",
    "category": "Flower",
    "price": "1000.00",
    "inventory": "1.89",
    "recreational": false,
    "medical": true,
    "hotDeal": false,
    "topPick": false,
    "status": "AVAILABLE",
    "vendor": "Golden Leaf",
  },
  {
    "name": "Nightmare Mints",
    "slug": "nightmare-mints",
    "category": "Flower",
    "price": "1000.00",
    "inventory": "8.54",
    "recreational": false,
    "medical": true,
    "hotDeal": true,
    "topPick": false,
    "status": "AVAILABLE",
    "vendor": "Golden Leaf",
  },
  {
    "name": "Party Animal",
    "slug": "party-animal",
    "category": "Flower",
    "price": "1000.00",
    "inventory": "21.5",
    "recreational": false,
    "medical": true,
    "hotDeal": false,
    "topPick": false,
    "status": "AVAILABLE",
    "vendor": "Golden Leaf",
  },
  {
    "name": "Furious George",
    "slug": "furious-george",
    "category": "Flower",
    "price": "700.00",
    "inventory": "5",
    "recreational": true,
    "medical": false,
    "hotDeal": true,
    "topPick": true,
    "status": "AVAILABLE",
    "vendor": "Taylor Farms",
  },
  {
    "name": "Apricot Scone",
    "slug": "apricot-scone",
    "category": "Flower",
    "price": "700.00",
    "inventory": "6",
    "recreational": true,
    "medical": false,
    "hotDeal": false,
    "topPick": false,
    "status": "AVAILABLE",
    "vendor": "Taylor Farms",
  },
  {
    "name": "Tropicana Banana",
    "slug": "tropicana-banana",
    "category": "Flower",
    "price": "700.00",
    "inventory": "5",
    "recreational": true,
    "medical": false,
    "hotDeal": false,
    "topPick": false,
    "status": "AVAILABLE",
    "vendor": "Taylor Farms",
  },
  {
    "name": "Jazz Cabbage",
    "slug": "jazz-cabbage",
    "category": "Flower",
    "price": "700.00",
    "inventory": "2",
    "recreational": true,
    "medical": false,
    "hotDeal": false,
    "topPick": false,
    "status": "AVAILABLE",
    "vendor": "Taylor Farms",
  },
  {
    "name": "Free Mac",
    "slug": "free-mac-tf",
    "category": "Flower",
    "price": "700.00",
    "inventory": "6",
    "recreational": true,
    "medical": false,
    "hotDeal": false,
    "topPick": false,
    "status": "AVAILABLE",
    "vendor": "Taylor Farms",
  },
  {
    "name": "Super Lemon Cream",
    "slug": "super-lemon-cream",
    "category": "Flower",
    "price": "700.00",
    "inventory": "1",
    "recreational": true,
    "medical": true,
    "hotDeal": true,
    "topPick": false,
    "status": "AVAILABLE",
    "vendor": "Taylor Farms",
  },
  {
    "name": "Durban Kush",
    "slug": "durban-kush-2a",
    "category": "Trim",
    "price": "175.00",
    "inventory": "0.98",
    "recreational": true,
    "medical": true,
    "hotDeal": false,
    "topPick": true,
    "status": "AVAILABLE",
    "vendor": "240 Arthur",
  },
  {
    "name": "Memberberry",
    "slug": "memberberry-2a",
    "category": "Trim",
    "price": "175.00",
    "inventory": "1.79",
    "recreational": false,
    "medical": true,
    "hotDeal": false,
    "topPick": false,
    "status": "AVAILABLE",
    "vendor": "240 Arthur",
  },
  {
    "name": "Truck Stop",
    "slug": "truck-stop",
    "category": "Trim",
    "price": "175.00",
    "inventory": "11",
    "recreational": false,
    "medical": false,
    "hotDeal": true,
    "topPick": false,
    "status": "AVAILABLE",
    "vendor": "240 Arthur",
  },
  {
    "name": "Wedding Cake",
    "slug": "wedding-cake-2a",
    "category": "Trim",
    "price": "175.00",
    "inventory": "2.55",
    "recreational": false,
    "medical": false,
    "hotDeal": false,
    "topPick": false,
    "status": "AVAILABLE",
    "vendor": "240 Arthur",
  },
  {
    "name": "Glueballs",
    "slug": "glueballs",
    "category": "Trim",
    "price": "175.00",
    "inventory": "26.65",
    "recreational": false,
    "medical": false,
    "hotDeal": false,
    "topPick": true,
    "status": "AVAILABLE",
    "vendor": "240 Arthur",
  },
  {
    "name": "Runtz",
    "slug": "runtz-trim",
    "category": "Trim",
    "price": "175.00",
    "inventory": "14",
    "recreational": false,
    "medical": false,
    "hotDeal": false,
    "topPick": false,
    "status": "AVAILABLE",
    "vendor": "240 Arthur",
  },
  {
    "name": "Blue Head OG",
    "slug": "blue-head-og",
    "category": "Trim",
    "price": "175.00",
    "inventory": "1.15",
    "recreational": false,
    "medical": false,
    "hotDeal": true,
    "topPick": false,
    "status": "AVAILABLE",
    "vendor": "Chronic Factory",
  },
  {
    "name": "Durban Kush",
    "slug": "durban-kush-cf",
    "category": "Trim",
    "price": "175.00",
    "inventory": "2.72",
    "recreational": false,
    "medical": true,
    "hotDeal": false,
    "topPick": false,
    "status": "AVAILABLE",
    "vendor": "Chronic Factory",
  },
  {
    "name": "Creamsicle",
    "slug": "creamsicle",
    "category": "Trim",
    "price": "175.00",
    "inventory": "1.07",
    "recreational": false,
    "medical": true,
    "hotDeal": true,
    "topPick": true,
    "status": "AVAILABLE",
    "vendor": "Chronic Factory",
  },
  {
    "name": "East Coast Sour Diesel",
    "slug": "east-coast-sour-diesel",
    "category": "Trim",
    "price": "175.00",
    "inventory": "1.62",
    "recreational": true,
    "medical": true,
    "hotDeal": false,
    "topPick": false,
    "status": "AVAILABLE",
    "vendor": "Chronic Factory",
  },
  {
    "name": "Gorrilla Glue #4",
    "slug": "gorrilla-glue-4",
    "category": "Trim",
    "price": "175.00",
    "inventory": "2.42",
    "recreational": true,
    "medical": false,
    "hotDeal": false,
    "topPick": false,
    "status": "AVAILABLE",
    "vendor": "Chronic Factory",
  },
  {
    "name": "East Coast Sour Diesel",
    "slug": "east-coast-sour-diesel-ff",
    "category": "Fresh Frozen",
    "price": "175.00",
    "inventory": "129",
    "recreational": true,
    "medical": false,
    "hotDeal": false,
    "topPick": false,
    "status": "AVAILABLE",
    "vendor": "240 Arthur",
  },
  {
    "name": "Runtz",
    "slug": "runtz-ff",
    "category": "Fresh Frozen",
    "price": "175.00",
    "inventory": "70",
    "recreational": true,
    "medical": true,
    "hotDeal": false,
    "topPick": false,
    "status": "AVAILABLE",
    "vendor": "240 Arthur",
  },
  {
    "name": "Purple Punch",
    "slug": "purple-punch",
    "category": "Fresh Frozen",
    "price": "60.00",
    "inventory": "510.39",
    "recreational": false,
    "medical": true,
    "hotDeal": true,
    "topPick": false,
    "status": "AVAILABLE",
    "vendor": "High Canyon",
  },
  {
    "name": "Tropicanna Cookies",
    "slug": "tropicanna-cookies",
    "category": "Fresh Frozen",
    "price": "60.00",
    "inventory": "47",
    "recreational": false,
    "medical": true,
    "hotDeal": false,
    "topPick": true,
    "status": "AVAILABLE",
    "vendor": "High Canyon",
  },
  {
    "name": "GMO",
    "slug": "gmo",
    "category": "Fresh Frozen",
    "price": "60.00",
    "inventory": "424.19",
    "recreational": false,
    "medical": false,
    "hotDeal": true,
    "topPick": false,
    "status": "AVAILABLE",
    "vendor": "High Canyon",
  },
  {
    "name": "Distillate Syringe - Recreational",
    "slug": "distillate-syringe-recreational",
    "category": "Concentrate",
    "price": "9.00",
    "inventory": "535",
    "recreational": true,
    "medical": false,
    "hotDeal": false,
    "topPick": false,
    "status": "AVAILABLE",
    "vendor": "CannXtracts",
  },
  {
    "name": "Distillate Syringe - Medical",
    "slug": "distillate-syringe-medical",
    "category": "Concentrate",
    "price": "9.00",
    "inventory": "535",
    "recreational": false,
    "medical": true,
    "hotDeal": false,
    "topPick": true,
    "status": "AVAILABLE",
    "vendor": "CannXtracts",
  },
  {
    "name": "Banana",
    "slug": "banana",
    "category": "Concentrate",
    "price": "13.00",
    "inventory": "308",
    "recreational": true,
    "medical": false,
    "hotDeal": false,
    "topPick": true,
    "status": "AVAILABLE",
    "vendor": "Golden Leaf",
  },
  {
    "name": "Banana Punch",
    "slug": "banana-punch",
    "category": "Concentrate",
    "price": "13.00",
    "inventory": "119",
    "recreational": true,
    "medical": false,
    "hotDeal": false,
    "topPick": false,
    "status": "AVAILABLE",
    "vendor": "Golden Leaf",
  },
  {
    "name": "Creamscicle OG",
    "slug": "creamscicle-og",
    "category": "Concentrate",
    "price": "13.00",
    "inventory": "500",
    "recreational": true,
    "medical": true,
    "hotDeal": true,
    "topPick": false,
    "status": "AVAILABLE",
    "vendor": "Golden Leaf",
  },
  {
    "name": "Fatso",
    "slug": "fatso",
    "category": "Concentrate",
    "price": "13.00",
    "inventory": "213",
    "recreational": true,
    "medical": true,
    "hotDeal": false,
    "topPick": false,
    "status": "AVAILABLE",
    "vendor": "Golden Leaf",
  },
  {
    "name": "Orange Cookie Banana",
    "slug": "orange-cookie-banana",
    "category": "Concentrate",
    "price": "13.00",
    "inventory": "275",
    "recreational": true,
    "medical": true,
    "hotDeal": false,
    "topPick": true,
    "status": "AVAILABLE",
    "vendor": "Golden Leaf",
  },
  {
    "name": "Spritzer",
    "slug": "spritzer-live-resin",
    "category": "Concentrate",
    "price": "13.00",
    "inventory": "334",
    "recreational": false,
    "medical": false,
    "hotDeal": true,
    "topPick": false,
    "status": "AVAILABLE",
    "vendor": "Golden Leaf",
  },
  {
    "name": "Hawaiian Ice",
    "slug": "hawaiian-ice-shatter",
    "category": "Concentrate",
    "price": "9.00",
    "inventory": "330",
    "recreational": false,
    "medical": false,
    "hotDeal": false,
    "topPick": false,
    "status": "AVAILABLE",
    "vendor": "Golden Leaf",
  },
  {
    "name": "Jelly Stomper",
    "slug": "jelly-stomper",
    "category": "Concentrate",
    "price": "9.00",
    "inventory": "367",
    "recreational": false,
    "medical": false,
    "hotDeal": false,
    "topPick": false,
    "status": "AVAILABLE",
    "vendor": "Golden Leaf",
  },
  {
    "name": "Lemon Dance",
    "slug": "lemon-dance",
    "category": "Concentrate",
    "price": "9.00",
    "inventory": "340",
    "recreational": false,
    "medical": false,
    "hotDeal": false,
    "topPick": false,
    "status": "AVAILABLE",
    "vendor": "Golden Leaf",
  },
  {
    "name": "Lemon MAC",
    "slug": "lemon-mac",
    "category": "Concentrate",
    "price": "9.00",
    "inventory": "300",
    "recreational": false,
    "medical": false,
    "hotDeal": true,
    "topPick": false,
    "status": "AVAILABLE",
    "vendor": "Golden Leaf",
  },
  {
    "name": "Orange Party",
    "slug": "orange-party",
    "category": "Concentrate",
    "price": "9.00",
    "inventory": "79",
    "recreational": false,
    "medical": false,
    "hotDeal": false,
    "topPick": false,
    "status": "AVAILABLE",
    "vendor": "Golden Leaf",
  },
  {
    "name": "White Fire",
    "slug": "white-fire",
    "category": "Concentrate",
    "price": "9.00",
    "inventory": "600",
    "recreational": false,
    "medical": false,
    "hotDeal": true,
    "topPick": true,
    "status": "AVAILABLE",
    "vendor": "Golden Leaf",
  },
  {
    "name": "Animal Cookies",
    "slug": "animal-cookies",
    "category": "Concentrate",
    "price": "9.00",
    "inventory": "48",
    "recreational": false,
    "medical": false,
    "hotDeal": false,
    "topPick": false,
    "status": "AVAILABLE",
    "vendor": "Golden Leaf",
  },
  {
    "name": "Banana Pop",
    "slug": "banana-pop",
    "category": "Concentrate",
    "price": "9.00",
    "inventory": "50",
    "recreational": true,
    "medical": false,
    "hotDeal": false,
    "topPick": false,
    "status": "AVAILABLE",
    "vendor": "Golden Leaf",
  },
  {
    "name": "Dry Ice",
    "slug": "dry-ice",
    "category": "Concentrate",
    "price": "9.00",
    "inventory": "79",
    "recreational": true,
    "medical": false,
    "hotDeal": false,
    "topPick": false,
    "status": "AVAILABLE",
    "vendor": "Golden Leaf",
  },
  {
    "name": "Flomingo",
    "slug": "flomingo",
    "category": "Concentrate",
    "price": "9.00",
    "inventory": "174",
    "recreational": true,
    "medical": false,
    "hotDeal": true,
    "topPick": true,
    "status": "AVAILABLE",
    "vendor": "Golden Leaf",
  },
  {
    "name": "Hawaiian Ice",
    "slug": "hawaiian-ice-wax",
    "category": "Concentrate",
    "price": "9.00",
    "inventory": "290",
    "recreational": true,
    "medical": false,
    "hotDeal": false,
    "topPick": false,
    "status": "AVAILABLE",
    "vendor": "Golden Leaf",
  },
  {
    "name": "Spritzer",
    "slug": "spritzer-wax",
    "category": "Concentrate",
    "price": "9.00",
    "inventory": "757",
    "recreational": true,
    "medical": false,
    "hotDeal": false,
    "topPick": false,
    "status": "AVAILABLE",
    "vendor": "Golden Leaf",
  },
  {
    "name": "Ethanol Distillate 85 - Recreational",
    "slug": "ethanol-distillate-recreational-85",
    "category": "Oil",
    "price": "2.50",
    "inventory": "3800",
    "recreational": true,
    "medical": false,
    "hotDeal": false,
    "topPick": true,
    "status": "AVAILABLE",
    "vendor": "Kunubu",
  },
  {
    "name": "Ethanol Distillate 84 - Recreational",
    "slug": "ethanol-distillate-recreational-84",
    "category": "Oil",
    "price": "2.50",
    "inventory": "4750",
    "recreational": true,
    "medical": false,
    "hotDeal": false,
    "topPick": false,
    "status": "AVAILABLE",
    "vendor": "Kunubu",
  },
  {
    "name": "C02 Distillate - Medical",
    "slug": "c02-distillate-medical",
    "category": "Oil",
    "price": "3.00",
    "inventory": "2500",
    "recreational": false,
    "medical": true,
    "hotDeal": true,
    "topPick": false,
    "status": "AVAILABLE",
    "vendor": "CannXtracts",
  }
]

